# Generated by Django 4.2.6 on 2024-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CookingStories", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="topic",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
