# Generated by Django 4.2.6 on 2024-08-08 08:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CookingStories", "0002_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
