# Generated by Django 4.2.6 on 2024-08-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CookingStories", "0002_delete_category_topic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_image",
            field=models.ImageField(blank=True, null=True, upload_to="authors/"),
        ),
    ]
